spring:
  datasource:
    url: jdbc:mysql://s4.java21.net:13306/be10-team1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: project_be10_team1
    password: N(zwIEW9ge2O3yXO
  jpa:
    hibernate:
      ddl-auto: validate

  dooray:
    webhook:
      url: https://nhnacademy.dooray.com/services/3204376758577275363/4071284119244117501/RibHlHtpSlCOQ1Kesn_0KQ