#server:
#  port: 8822

spring:
#  datasource:
#    url: jdbc:mysql://s4.java21.net:13306/be10-team1
#    username: your_mysql_username
#    password: your_mysql_password
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발 중이면 update, 배포용은 validate나 none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  session:
    store-type: redis  # 세션 저장소를 redis로 지정
    timeout: 1800s     # 세션 유지 시간 설정 (선택)
#  data:
#    redis:
#      host: s4.java21.net
#      port: 6379

  dooray:
    webhook:
      url: https://nhnacademy.dooray.com/services/3204376758577275363/4071284119244117501/RibHlHtpSlCOQ1Kesn_0KQ


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

