### 회원가입
POST http://localhost:8080/members
Content-Type: application/json

{
  "name": "홍길동",
  "birth": "1995-08-15",
  "email": "honggildong@example.com",
  "password": "securePwd123!",
  "contact": "010-1234-5678"
}

### 테스트를 위해 DB에서 회원 마지막로그인 3개월 전으로 설정
//UPDATE members SET last_login_at = DATE_SUB(NOW(), INTERVAL 3 MONTH) WHERE email = 'honggildong@example.com';

### 회원 조회 (회원 휴면상태 체크)
GET http://localhost:8080/members/1
Content-Type: application/json

### 휴면해제 인증번호 전송
POST http://localhost:8080/members/1/inactive/verification
Content-Type: application/json

### 휴면해제 인증번호 검증
POST http://localhost:8080/members/1/inactive/verification/verify
Content-Type: application/json

{
  "code": "813185"
}
