### 회원 목록 조회
GET http://localhost:10303/admin/members
Content-Type: application/json

### 회원 단일 조회
GET http://localhost:8080/members/1
Content-Type: application/json

### 회원가입
POST http://localhost:10303/members
Content-Type: application/json

{
  "name" : "hge",
  "birth" : "2000-03-13",
  "email": "newuser@example.com",
  "password": "Password123!",
  "contact": "010-1234-5678"
}

### 회원 이메일로 조회
GET http://localhost:10303/members?memberEmail=newuser@example.com


### 회원 로그인
POST http://localhost:8080/members/login
Content-Type: application/json

{
  "email": "newuser@example.com",
  "password": "Password123!"
}

### 회원 정보수정
PATCH http://localhost:8080/members/1
Content-Type: application/json

{
  "email": "royal@example.com",
  "contact": "010-1234-5678"
}

### 회원 삭제
DELETE http://localhost:8080/members/1
Content-Type: application/json



