### 관리자 포인트정책 조회
GET http://localhost:10303/admin/point-policies
Content-Type: application/json

### 관리자 포인트정책 단일조회
GET http://localhost:10303/admin/point-policies/book_default_rate
Content-Type: application/json


### 관리자 포인트정책 수정
PATCH http://localhost:10303/admin/point-policies/join_point
Content-Type: application/json

{
  "value": "0.30",
  "valueType": "RATE"

}
